import { expect } from "chai";
import { ethers } from "hardhat";
import { Verifier } from "../../typechain-types";

describe("Verifier", function () {
  let verifier: Verifier;

  // These are dummy values - the current Verifier stub only checks input[0]
  const DUMMY_A: [bigint, bigint] = [1n, 2n];
  const DUMMY_B: [[bigint, bigint], [bigint, bigint]] = [[3n, 4n], [5n, 6n]];
  const DUMMY_C: [bigint, bigint] = [7n, 8n];

  beforeEach(async function () {
    const VerifierFactory = await ethers.getContractFactory("Verifier");
    verifier = (await VerifierFactory.deploy()) as Verifier;
  });

  describe("verifyProof", function () {
    it("should return true when input[0] = 1 (compliant)", async function () {
      const result = await verifier.verifyProof(
        DUMMY_A, DUMMY_B, DUMMY_C, [1n]
      );
      expect(result).to.be.true;
    });

    it("should return false when input[0] = 0 (non-compliant)", async function () {
      const result = await verifier.verifyProof(
        DUMMY_A, DUMMY_B, DUMMY_C, [0n]
      );
      expect(result).to.be.false;
    });

    it("should be a pure function (no gas cost for reads)", async function () {
      // Pure functions can be called without a transaction
      const result = await verifier.verifyProof.staticCall(
        DUMMY_A, DUMMY_B, DUMMY_C, [1n]
      );
      expect(result).to.be.true;
    });
  });

  describe("Integration point documentation", function () {
    it("should accept the full Groth16 proof signature (a, b, c, input)", async function () {
      // This test documents the interface contract for the production BN254 verifier
      // When the real verifier is generated by snarkjs, it must satisfy this interface.
      const result = await verifier.verifyProof(
        DUMMY_A, DUMMY_B, DUMMY_C, [1n]
      );
      expect(typeof result).to.equal("boolean");
    });
  });
});
